spec:
  structures:
    - content_blocks
  label: Split
  description: Arranges content in two columns.
  icon: columns
  tags: []

blueprint:
  first:
    content_blocks: []
    minWidth: null
  last:
    content_blocks: []
    minWidth: null
  distributionMode: "half"
  fixedWidth: null
  verticalAlignment: "top"
  reverse: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the split to help identify it in the editor.
    type: text
  distributionMode:
    comment: Predefined distribution mode for both columns.
    type: select
    options:
      values:
        - quarter-three-quarters
        - third-two-thirds
        - half
        - two-thirds-third
        - three-quarters-quarter
        - fixed-flexible
        - flexible-fixed
  fixedWidth:
    comment: Fixed width in pixels (used when distribution mode includes 'fixed').
    type: number
  first:
    comment: Configuration for the first column.
    type: object
    _inputs:
      content_blocks:
        comment: Array of content blocks to render in the first column.
        type: array
      minWidth:
        comment: Minimum width in pixels for the first column.
        type: number
  last:
    comment: Configuration for the last column.
    type: object
    _inputs:
      content_blocks:
        comment: Array of content blocks to render in the last column.
        type: array
      minWidth:
        comment: Minimum width in pixels for the last column.
        type: number
  verticalAlignment:
    comment: Vertical alignment of the columns.
    type: select
    options:
      values:
        - top
        - center
        - bottom
        - stretch
  reverse:
    comment: "Swaps the order of the columns."
    type: checkbox
