spec:
  structures:
    - formBlocks
  label: Submit
  description: "A submit button for forms."
  icon: check
  tags: []

blueprint:
  text: Submit
  variant: primary
  size: md
  iconName:
  iconPosition: before
  hideText: false
  disabled: false

preview:

_inputs:
  text:
    type: text
    comment: The text that goes inside the submit button.
  variant:
    type: select
    options:
      values:
        - primary
        - secondary
        - tertiary
        - ghost
        - text
    comment: The presentation of the submit button.
  size:
    type: select
    options:
      values:
        - sm
        - md
        - lg
    comment: The size of the submit button.
  iconName:
    type: select
    options:
      values: _select_data.icons
    comment: The name of the icon to display. See the Icon component documentation for more information.
  iconPosition:
    type: select
    options:
      values:
        - before
        - after
    comment: The position of the icon relative to the text.
  hideText:
    type: switch
    comment: Whether to hide the button text and show only the icon.
  disabled:
    type: switch
    comment: Whether the submit button is disabled.
