spec:
  structures:
    - formBlocks
  label: Select
  description: "A dropdown select field with an optional label."
  icon: rectangle
  tags: []

blueprint:
  label:
  name:
  options: []
  placeholder:
  required: false
  value:

preview:

_inputs:
  label:
    type: text
    comment: The label text for the select field.
  name:
    type: text
    comment: The name attribute for the select field.
  options:
    type: array
    comment: Array of select options with value and label.
    options:
      structures: _structures.option
  placeholder:
    type: text
    comment: Placeholder text for the select field.
  required:
    type: switch
    comment: Whether the field is required.
  value:
    type: text
    comment: The default selected value.

_structures:
  option:
    values:
      - label: Option
        icon: list
        value:
          value:
          label:
        _inputs:
          value:
            type: text
            comment: The value attribute for this option (submitted with the form).
          label:
            type: text
            comment: The display text for this option.
