# Metadata about this component, to be used in the CMS
spec:
  label: Mobile Navigation
  description: A mobile navigation with hamburger menu and slide-out panel.
  icon: device-phone-mobile
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  logoSource:
  logoAlt:
  navData: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  logoSource:
  logoAlt: "Logo"
  navData:
    - name: "Home"
      path: "#"
      children: []
    - name: "Resources"
      path: "#"
      children:
        - name: "Blog"
          path: "#"
          children: []
        - name: "Documentation"
          path: "#"
          children: []
        - name: "Support"
          path: "#"
          children: []
    - name: "Contact"
      path: "#"
      children: []

_inputs:
  logoSource:
    type: text
    label: Logo Source
    comment: Path to the logo image.
  logoAlt:
    type: text
    label: Logo Alt Text
    comment: Alternative text for the logo image.
  navData:
    type: array
    label: Navigation Data
    comment: Array of navigation items with name, path, and optional children (up to 3 levels).
    options:
      structures: _structures.navItemLevel1

_structures:
  navItemLevel1:
    values:
      - label: Navigation Item (Level 1)
        icon: link
        value:
          name:
          path:
          children:
        _inputs:
          name:
            type: text
            comment: The display text for the navigation item.
          path:
            type: text
            comment: The URL/path for the navigation item.
          children:
            type: array
            comment: Optional nested navigation items (level 2).
            options:
              structures: _structures.navItemLevel2
  navItemLevel2:
    values:
      - label: Navigation Item (Level 2)
        icon: link
        value:
          name:
          path:
          children:
        _inputs:
          name:
            type: text
            comment: The display text for the navigation item.
          path:
            type: text
            comment: The URL/path for the navigation item.
          children:
            type: array
            comment: Optional nested navigation items (level 3, final level).
            options:
              structures: _structures.navItemLevel3
  navItemLevel3:
    values:
      - label: Navigation Item (Level 3)
        icon: link
        value:
          name:
          path:
        _inputs:
          name:
            type: text
            comment: The display text for the navigation item.
          path:
            type: text
            comment: The URL/path for the navigation item.
